"""The single local SQLite owner for metadata-only operation and cleanup state."""

from __future__ import annotations

import hashlib
import hmac
import json
import os
import re
import secrets
import sqlite3
import stat
import sys
import threading
import time
from collections.abc import Iterator
from contextlib import contextmanager
from dataclasses import asdict, dataclass, replace
from pathlib import Path
from typing import Any

from ..domain import Artifact, ArtifactKind, ArtifactState, ArtifactVerification, ArtifactVerificationStatus, DomainErrorCode, OperationState

RETENTION_SECONDS = 7 * 24 * 60 * 60
SCHEMA_VERSION = 3
_IDENTIFIER = re.compile(r"^[A-Za-z0-9_:\-]{1,256}$")
_LABEL = re.compile(r"^[A-Za-z0-9_.:\-]{1,96}$")
_CLEANUP_STATES = {"pending", "running", "completed", "failed", "retained", "cancelled"}


class StateStoreError(RuntimeError):
    """A safe storage error, never including database data or SQL arguments."""


def _require_private_filesystem() -> None:
    if os.name != "posix" or not all(hasattr(os, name) for name in ("O_NOFOLLOW", "getuid")):
        raise StateStoreError(
            "Private state storage currently requires macOS/Linux POSIX file protections; "
            "the Windows authenticated runtime is not supported."
        )


def _identifier(value: str) -> str:
    if not isinstance(value, str) or not _IDENTIFIER.fullmatch(value):
        raise ValueError("Invalid state identifier.")
    return value


@dataclass(frozen=True)
class ArtifactLocator:
    id: str
    kind: str
    state: str
    uri: str | None = None
    local_path: str | None = None
    source_chat_id: str | None = None
    verification: str = "unverified"

    def __post_init__(self) -> None:
        _identifier(self.id)
        ArtifactKind(self.kind)
        ArtifactState(self.state)
        ArtifactVerificationStatus(self.verification)
        if self.source_chat_id is not None:
            _identifier(self.source_chat_id)
        if self.uri and not self.uri.startswith(("https://", "http://", "file://")):
            raise ValueError("Artifact URI is not a persistent locator.")

    @classmethod
    def from_artifact(cls, value: Artifact) -> ArtifactLocator:
        # A data URI would persist the generated bytes, contrary to this store's
        # contract. An ordinary URI/path is only a locator; titles/details stay
        # in the caller's current result and are never serialized here.
        if value.uri and not value.uri.startswith(("https://", "http://", "file://")):
            raise ValueError("Artifact URI is not a persistent locator.")
        return cls(_identifier(value.id), value.kind.value, value.state.value, value.uri,
                   value.local_path, value.source_chat_id, value.verification.status.value)

    def artifact(self) -> Artifact:
        return Artifact(id=self.id, kind=ArtifactKind(self.kind), state=ArtifactState(self.state),
                        uri=self.uri, local_path=self.local_path, source_chat_id=self.source_chat_id,
                        verification=ArtifactVerification(ArtifactVerificationStatus(self.verification)))


@dataclass(frozen=True)
class OperationRecord:
    operation_id: str
    scope_id: str
    operation_type: str
    state: OperationState
    created_at: float
    updated_at: float
    expires_at: float
    provider_operation_id: str | None = None
    upstream_chat_id: str | None = None
    attempt_count: int = 0
    error_code: str | None = None
    verification_status: str = "not_observed"
    artifacts: tuple[ArtifactLocator, ...] = ()
    version: int = 0
    idempotency_key: str | None = None
    output_dir: str | None = None
    retain_chat: bool = True
    delete_after_seconds: int | None = None
    lease_id: str | None = None
    lease_until: float | None = None


@dataclass(frozen=True)
class CleanupJobRecord:
    job_id: str
    scope_id: str
    resource_id: str
    state: str
    due_at: float
    created_at: float
    updated_at: float
    expires_at: float
    resource_type: str = "chat"
    attempts: int = 0
    diagnostic_id: str | None = None
    verification_status: str = "not_observed"
    source: str = ""
    error_code: str | None = None
    version: int = 0
    lease_id: str | None = None
    lease_until: float | None = None


class StateStore:
    """Lazy, permission-restricted SQLite database with transactional repositories."""

    def __init__(self, path: str | Path, *, clock: Any = time.time):
        self.path = Path(path).expanduser().absolute()
        self.clock = clock
        self._lock = threading.RLock()
        self._last_prune_at: float | None = None
        self.operations = OperationRepository(self)
        self.cleanup_jobs = CleanupRepository(self)

    def _prepare(self) -> None:
        _require_private_filesystem()
        self.path.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
        try:
            fd = os.open(self.path, os.O_CREAT | os.O_EXCL | os.O_RDWR | os.O_NOFOLLOW, 0o600)
        except FileExistsError:
            info = self.path.lstat()
            if not stat.S_ISREG(info.st_mode) or info.st_uid != os.getuid() or info.st_mode & 0o077:
                raise StateStoreError("State database has unsafe file permissions.") from None
        else:
            os.close(fd)

    @contextmanager
    def transaction(self) -> Iterator[sqlite3.Connection]:
        with self._lock:
            self._prepare()
            connection = sqlite3.connect(self.path, timeout=3, isolation_level=None)
            connection.row_factory = sqlite3.Row
            try:
                connection.execute("PRAGMA secure_delete=ON")
                connection.execute("PRAGMA journal_mode=WAL")
                connection.execute("BEGIN IMMEDIATE")
                version = int(connection.execute("PRAGMA user_version").fetchone()[0])
                if version > SCHEMA_VERSION:
                    raise StateStoreError("State database schema is newer than this installation.")
                if version == 0:
                    connection.execute("""CREATE TABLE IF NOT EXISTS operations (
                        operation_id TEXT PRIMARY KEY, scope_id TEXT NOT NULL, operation_type TEXT NOT NULL,
                        state TEXT NOT NULL, created_at REAL NOT NULL, updated_at REAL NOT NULL,
                        expires_at REAL NOT NULL, provider_operation_id TEXT, upstream_chat_id TEXT,
                        attempt_count INTEGER NOT NULL, error_code TEXT, verification_status TEXT NOT NULL,
                        artifacts TEXT NOT NULL, version INTEGER NOT NULL, idempotency_key TEXT,
                        UNIQUE(scope_id, idempotency_key))""")
                    connection.execute("""CREATE TABLE IF NOT EXISTS cleanup_jobs (
                        job_id TEXT PRIMARY KEY, scope_id TEXT NOT NULL, resource_id TEXT NOT NULL,
                        state TEXT NOT NULL, due_at REAL NOT NULL, created_at REAL NOT NULL,
                        updated_at REAL NOT NULL, expires_at REAL NOT NULL, resource_type TEXT NOT NULL,
                        attempts INTEGER NOT NULL, diagnostic_id TEXT, verification_status TEXT NOT NULL,
                        source TEXT NOT NULL, error_code TEXT, version INTEGER NOT NULL,
                        lease_id TEXT, lease_until REAL, UNIQUE(scope_id, resource_id))""")
                    connection.execute("CREATE INDEX IF NOT EXISTS cleanup_due ON cleanup_jobs(scope_id,state,due_at)")
                    connection.execute("PRAGMA user_version=1")
                if version < 2:
                    connection.execute("ALTER TABLE operations ADD COLUMN output_dir TEXT")
                    connection.execute("ALTER TABLE operations ADD COLUMN retain_chat INTEGER NOT NULL DEFAULT 1")
                    connection.execute("ALTER TABLE operations ADD COLUMN delete_after_seconds INTEGER")
                    connection.execute("PRAGMA user_version=2")
                if version < 3:
                    connection.execute("ALTER TABLE operations ADD COLUMN lease_id TEXT")
                    connection.execute("ALTER TABLE operations ADD COLUMN lease_until REAL")
                    connection.execute(f"PRAGMA user_version={SCHEMA_VERSION}")
                now = self.clock()
                prune = self._last_prune_at is None or now - self._last_prune_at >= 3600
                if prune:
                    connection.execute("DELETE FROM operations WHERE expires_at<=?", (now,))
                    connection.execute("DELETE FROM cleanup_jobs WHERE expires_at<=? AND state IN ('completed','cancelled','retained')", (now,))
                yield connection
                connection.execute("COMMIT")
                if prune:
                    self._last_prune_at = now
            except sqlite3.Error:
                if connection.in_transaction:
                    connection.execute("ROLLBACK")
                raise StateStoreError("Local operation state could not be accessed.") from None
            finally:
                connection.close()

    def scope_for(self, psid: str) -> str | None:
        if not psid or not isinstance(psid, str):
            return None
        _require_private_filesystem()
        key_path = self.path.with_suffix(self.path.suffix + ".key")
        self.path.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
        if not key_path.exists():
            temporary = key_path.with_name(key_path.name + "." + secrets.token_hex(12))
            fd = os.open(temporary, os.O_CREAT | os.O_EXCL | os.O_WRONLY, 0o600)
            try:
                with os.fdopen(fd, "wb") as output:
                    output.write(secrets.token_bytes(32))
                    output.flush()
                    os.fsync(output.fileno())
                try:
                    os.link(temporary, key_path)
                except FileExistsError:
                    pass
            finally:
                temporary.unlink(missing_ok=True)
        info = key_path.lstat()
        if not stat.S_ISREG(info.st_mode) or info.st_uid != os.getuid() or info.st_mode & 0o077:
            raise StateStoreError("State identity key has unsafe file permissions.")
        key = key_path.read_bytes()
        if len(key) != 32:
            raise StateStoreError("State identity key is invalid.")
        return "scope_" + hmac.new(key, psid.encode(), hashlib.sha256).hexdigest()


def _operation(row: sqlite3.Row) -> OperationRecord:
    value = dict(row)
    try:
        value["state"] = OperationState(value["state"])
        value["retain_chat"] = bool(value["retain_chat"])
        value["artifacts"] = tuple(ArtifactLocator(**item) for item in json.loads(value["artifacts"]))
        for item in value["artifacts"]:
            item.artifact()
        return OperationRecord(**value)
    except (TypeError, ValueError, KeyError):
        raise StateStoreError("Stored operation metadata is invalid.") from None


class OperationRepository:
    def __init__(self, store: StateStore):
        self.store = store

    def create(self, record: OperationRecord) -> tuple[OperationRecord, bool]:
        for value in (record.operation_id, record.scope_id, record.operation_type):
            _identifier(value)
        if record.idempotency_key:
            _identifier(record.idempotency_key)
        OperationState(record.state)
        _identifier(record.verification_status)
        if record.error_code is not None:
            DomainErrorCode(record.error_code)
        if record.delete_after_seconds is not None and record.delete_after_seconds < 0:
            raise ValueError("Invalid cleanup delay.")
        if record.output_dir and not Path(record.output_dir).is_absolute():
            raise ValueError("Persistent artifact destination must be absolute.")
        values = asdict(record)
        values["state"] = record.state.value
        values["artifacts"] = json.dumps(values["artifacts"], separators=(",", ":"))
        with self.store.transaction() as conn:
            if record.idempotency_key:
                row = conn.execute("SELECT * FROM operations WHERE scope_id=? AND idempotency_key=?",
                                   (record.scope_id, record.idempotency_key)).fetchone()
                if row:
                    existing = _operation(row)
                    if existing.operation_type != record.operation_type:
                        raise ValueError("Idempotency key belongs to another operation kind.")
                    return existing, False
            columns = ",".join(values)
            conn.execute(f"INSERT INTO operations ({columns}) VALUES ({','.join('?' for _ in values)})", tuple(values.values()))
        return record, True

    def get(self, scope_id: str, operation_id: str) -> OperationRecord | None:
        with self.store.transaction() as conn:
            row = conn.execute("SELECT * FROM operations WHERE scope_id=? AND operation_id=?", (scope_id, operation_id)).fetchone()
        return _operation(row) if row else None

    def update(self, scope_id: str, operation_id: str, *, expected_version: int | None = None, lease_id: str | None = None, **changes: Any) -> OperationRecord | None:
        allowed = {"state", "provider_operation_id", "upstream_chat_id", "attempt_count", "error_code", "verification_status", "artifacts", "output_dir"}
        if not changes.keys() <= allowed:
            raise ValueError("Unsupported persistent operation field.")
        for name in ("provider_operation_id", "upstream_chat_id", "error_code", "verification_status"):
            if changes.get(name) is not None:
                _identifier(changes[name])
        if changes.get("error_code") is not None:
            DomainErrorCode(changes["error_code"])
        if changes.get("output_dir") and not Path(changes["output_dir"]).is_absolute():
            raise ValueError("Persistent artifact destination must be absolute.")
        with self.store.transaction() as conn:
            row = conn.execute("SELECT * FROM operations WHERE scope_id=? AND operation_id=?", (scope_id, operation_id)).fetchone()
            if not row or (expected_version is not None and row["version"] != expected_version) or (lease_id is not None and row["lease_id"] != lease_id):
                return None
            record = _operation(row)
            if "state" in changes:
                desired = OperationState(changes["state"])
                terminal = {OperationState.COMPLETED, OperationState.CANCELLED, OperationState.EXPIRED}
                if record.state in terminal and desired != record.state:
                    raise ValueError("Terminal operation state cannot be changed.")
                if record.state == OperationState.CANCEL_REQUESTED and desired not in {
                    OperationState.CANCEL_REQUESTED, OperationState.CANCELLED, OperationState.COMPLETED,
                    OperationState.PARTIAL, OperationState.FAILED, OperationState.TIMED_OUT,
                }:
                    desired = OperationState.CANCEL_REQUESTED
                changes["state"] = desired
            updated = replace(record, **changes, updated_at=self.store.clock(), version=record.version + 1)
            values = dict(changes)
            if "state" in values:
                values["state"] = updated.state.value
            if "artifacts" in values:
                values["artifacts"] = json.dumps([asdict(a) for a in updated.artifacts], separators=(",", ":"))
            values.update(updated_at=updated.updated_at, version=updated.version)
            conn.execute(f"UPDATE operations SET {','.join(k+'=?' for k in values)} WHERE scope_id=? AND operation_id=?",
                         (*values.values(), scope_id, operation_id))
        return updated

    def claim(self, scope_id: str, operation_id: str, *, lease_id: str, lease_until: float, now: float) -> OperationRecord | None:
        _identifier(lease_id)
        with self.store.transaction() as conn:
            row = conn.execute("SELECT * FROM operations WHERE scope_id=? AND operation_id=?", (scope_id, operation_id)).fetchone()
            if not row or row["state"] in {"completed", "cancelled", "expired"} or row["expires_at"] <= now:
                return None
            if (row["lease_until"] or 0) > now or lease_until <= now:
                return None
            conn.execute("UPDATE operations SET lease_id=?,lease_until=?,version=version+1,updated_at=? WHERE scope_id=? AND operation_id=?",
                         (lease_id, lease_until, now, scope_id, operation_id))
            current = conn.execute("SELECT * FROM operations WHERE scope_id=? AND operation_id=?", (scope_id, operation_id)).fetchone()
        return _operation(current)

    def renew(self, scope_id: str, operation_id: str, *, lease_id: str, lease_until: float) -> bool:
        with self.store.transaction() as conn:
            count = conn.execute("UPDATE operations SET lease_until=? WHERE scope_id=? AND operation_id=? AND lease_id=?",
                                 (lease_until, scope_id, operation_id, lease_id)).rowcount
        return count == 1

    def release(self, scope_id: str, operation_id: str, *, lease_id: str) -> None:
        with self.store.transaction() as conn:
            conn.execute("UPDATE operations SET lease_id=NULL,lease_until=NULL WHERE scope_id=? AND operation_id=? AND lease_id=?",
                         (scope_id, operation_id, lease_id))

    def prune(self, now: float | None = None) -> int:
        with self.store.transaction() as conn:
            return conn.execute("DELETE FROM operations WHERE expires_at<=?", (self.store.clock() if now is None else now,)).rowcount


class CleanupRepository:
    def __init__(self, store: StateStore):
        self.store = store

    def upsert(self, record: CleanupJobRecord) -> CleanupJobRecord:
        for value in (record.job_id, record.scope_id, record.resource_id, record.resource_type):
            _identifier(value)
        if record.source and not _LABEL.fullmatch(record.source):
            raise ValueError("Cleanup source must be a controlled operation kind.")
        if record.state not in _CLEANUP_STATES:
            raise ValueError("Invalid cleanup state.")
        if record.state == "completed" and record.verification_status != "verified_absent":
            raise ValueError("Cleanup completion requires observed absence.")
        values = asdict(record)
        with self.store.transaction() as conn:
            conn.execute(f"INSERT OR IGNORE INTO cleanup_jobs ({','.join(values)}) VALUES ({','.join('?' for _ in values)})", tuple(values.values()))
            row = conn.execute("SELECT * FROM cleanup_jobs WHERE scope_id=? AND resource_id=?", (record.scope_id, record.resource_id)).fetchone()
        return CleanupJobRecord(**dict(row))

    def get(self, scope_id: str, resource_id: str) -> CleanupJobRecord | None:
        with self.store.transaction() as conn:
            row = conn.execute("SELECT * FROM cleanup_jobs WHERE scope_id=? AND resource_id=?", (scope_id, resource_id)).fetchone()
        return CleanupJobRecord(**dict(row)) if row else None

    def get_by_job_id(self, scope_id: str, job_id: str) -> CleanupJobRecord | None:
        with self.store.transaction() as conn:
            row = conn.execute("SELECT * FROM cleanup_jobs WHERE scope_id=? AND job_id=?", (scope_id, job_id)).fetchone()
        return CleanupJobRecord(**dict(row)) if row else None

    def list(self, scope_id: str, *, limit: int = 50, offset: int = 0, states: tuple[str, ...] = ()) -> tuple[CleanupJobRecord, ...]:
        if not 1 <= limit <= 101 or offset < 0:
            raise ValueError("Invalid cleanup pagination.")
        suffix = f" AND state IN ({','.join('?' for _ in states)})" if states else ""
        with self.store.transaction() as conn:
            rows = conn.execute("SELECT * FROM cleanup_jobs WHERE scope_id=?" + suffix + " ORDER BY created_at,job_id LIMIT ? OFFSET ?",
                                (scope_id, *states, limit, offset)).fetchall()
        return tuple(CleanupJobRecord(**dict(row)) for row in rows)

    def update(self, scope_id: str, resource_id: str, *, expected_version: int | None = None, lease_id: str | None = None, **changes: Any) -> CleanupJobRecord | None:
        allowed = {"state", "due_at", "attempts", "diagnostic_id", "verification_status", "source", "error_code", "lease_id", "lease_until", "expires_at"}
        if not changes.keys() <= allowed:
            raise ValueError("Unsupported persistent cleanup field.")
        if "state" in changes and changes["state"] not in _CLEANUP_STATES:
            raise ValueError("Invalid cleanup state.")
        for name in ("diagnostic_id", "verification_status", "error_code"):
            if changes.get(name) is not None:
                _identifier(changes[name])
        if changes.get("source") and not _LABEL.fullmatch(changes["source"]):
            raise ValueError("Cleanup source must be a controlled operation kind.")
        if changes.get("state") == "completed" and changes.get("verification_status") != "verified_absent":
            raise ValueError("Cleanup completion requires observed absence.")
        with self.store.transaction() as conn:
            row = conn.execute("SELECT * FROM cleanup_jobs WHERE scope_id=? AND resource_id=?", (scope_id, resource_id)).fetchone()
            if not row or (expected_version is not None and row["version"] != expected_version) or (lease_id is not None and (row["lease_id"] != lease_id or row["state"] != "running")):
                return None
            if row["state"] == "completed" and changes.get("state", "completed") != "completed":
                return None
            record = CleanupJobRecord(**dict(row))
            updated = replace(record, **changes, updated_at=self.store.clock(), version=record.version + 1)
            if updated.state != "running":
                updated = replace(updated, lease_id=None, lease_until=None)
            values = asdict(updated)
            del values["job_id"]
            del values["scope_id"]
            del values["resource_id"]
            conn.execute(f"UPDATE cleanup_jobs SET {','.join(k+'=?' for k in values)} WHERE scope_id=? AND resource_id=?", (*values.values(), scope_id, resource_id))
        return updated

    def claim(self, scope_id: str, resource_id: str, *, expected_version: int, lease_id: str, lease_until: float, now: float) -> CleanupJobRecord | None:
        _identifier(lease_id)
        with self.store.transaction() as conn:
            row = conn.execute("SELECT * FROM cleanup_jobs WHERE scope_id=? AND resource_id=?", (scope_id, resource_id)).fetchone()
            if not row or row["version"] != expected_version:
                return None
            eligible = row["state"] in {"pending", "failed"} and row["due_at"] <= now
            eligible = eligible or (row["state"] == "running" and (row["lease_until"] or 0) <= now)
            if not eligible or lease_until <= now:
                return None
            conn.execute("UPDATE cleanup_jobs SET state='running',attempts=attempts+1,version=version+1,updated_at=?,lease_id=?,lease_until=? WHERE scope_id=? AND resource_id=?",
                         (now, lease_id, lease_until, scope_id, resource_id))
            current = conn.execute("SELECT * FROM cleanup_jobs WHERE scope_id=? AND resource_id=?", (scope_id, resource_id)).fetchone()
        return CleanupJobRecord(**dict(current))

    def renew(self, scope_id: str, resource_id: str, *, lease_id: str, lease_until: float) -> CleanupJobRecord | None:
        return self.update(scope_id, resource_id, lease_id=lease_id, lease_until=lease_until)

    def delete(self, scope_id: str, resource_id: str) -> None:
        with self.store.transaction() as conn:
            conn.execute("DELETE FROM cleanup_jobs WHERE scope_id=? AND resource_id=?", (scope_id, resource_id))

    def prune(self, now: float | None = None) -> int:
        with self.store.transaction() as conn:
            return conn.execute("DELETE FROM cleanup_jobs WHERE expires_at<=? AND state IN ('completed','cancelled','retained')", (self.store.clock() if now is None else now,)).rowcount


_stores: dict[Path, StateStore] = {}
_stores_lock = threading.Lock()


def get_default_state_store() -> StateStore:
    configured = os.environ.get("GEMINI_STATE_DB_PATH")
    if configured:
        path = Path(configured).expanduser().absolute()
    else:
        base = Path.home() / ("Library/Application Support" if sys.platform == "darwin" else ".local/state")
        path = base / "gemini-web-mcp/state.sqlite3"
    with _stores_lock:
        return _stores.setdefault(path, StateStore(path))


def authentication_scope(psid: str | None = None, *, store: StateStore | None = None) -> str | None:
    material = os.environ.get("GEMINI_PSID", "") if psid is None else psid
    return (store or get_default_state_store()).scope_for(material) if material else None
