"""
Static manifest data extracted from manage.py to keep the tools module focused on logic.

These structures are pure data literals (no function/constant references) and are safe
to import anywhere. They describe the observed Gemini Web Pro UI surface, the read-only
RPC probes, and the agent-facing tool manifest with safety/privacy metadata.
"""

from typing import Any

WEB_UI_CAPABILITIES = {
    "observed_at": "2026-06-18",
    "account_tier": "Gemini Web Pro",
    "locale": "zh-CN",
    "models": [
        {
            "alias": "flash-lite",
            "display_name": "3.1 Flash-Lite",
            "description": "极速回答",
            "thinking_mode_id": 6,
            "advanced_only": False,
        },
        {
            "alias": "flash",
            "display_name": "3.5 Flash",
            "description": "全方位帮助",
            "thinking_mode_id": 1,
            "advanced_only": False,
        },
        {
            "alias": "pro",
            "display_name": "3.1 Pro",
            "description": "高等数学与代码",
            "thinking_mode_id": 3,
            "advanced_only": True,
        },
    ],
    "thinking_levels": [
        {
            "id": "standard",
            "display_name": "标准",
            "description": "最适合回答大多数问题",
            "level_id": 1,
        },
        {
            "id": "extended",
            "display_name": "扩展",
            "description": "擅长解决复杂问题",
            "level_id": 2,
        },
    ],
    "tool_menu": [
        {"name": "upload_file", "label": "上传文件", "coverage": "gemini_upload_file"},
        {"name": "google_drive", "label": "从云端硬盘添加", "coverage": "ui_only"},
        {"name": "import_code", "label": "导入代码", "coverage": "gemini_upload_file"},
        {"name": "create_image", "label": "图片", "coverage": "gemini_generate_media"},
        {"name": "create_video", "label": "视频", "coverage": "gemini_generate_media"},
        {"name": "canvas", "label": "Canvas", "coverage": "library_capability"},
        {"name": "deep_research", "label": "Deep Research", "coverage": "gemini_deep_research"},
        {"name": "create_music", "label": "音乐", "coverage": "gemini_generate_music"},
        {"name": "guided_learning", "label": "学习辅导", "coverage": "library_capability"},
        {"name": "personalization_labs", "label": "个性化 / Labs", "coverage": "probe_only"},
    ],
    "settings_menu": [
        {"name": "activity", "label": "活动记录", "coverage": "external_google_activity"},
        {"name": "personalization", "label": "个性化智能服务", "coverage": "probe_only"},
        {"name": "memory_import", "label": "将记忆导入 Gemini", "coverage": "probe_only"},
        {"name": "usage_limits", "label": "用量限额", "coverage": "gemini_get_usage_limits"},
        {
            "name": "scheduled_actions",
            "label": "定时操作",
            "coverage": "gemini_list_scheduled_actions / gemini_get_scheduled_action / gemini_create_scheduled_action / gemini_delete_scheduled_action",
        },
        {"name": "gems", "label": "Gem", "coverage": "gemini_manage_gems"},
        {"name": "public_links", "label": "你的公开链接", "coverage": "gemini_list_public_links"},
        {"name": "theme", "label": "主题", "coverage": "ui_only"},
        {"name": "subscription", "label": "管理订阅", "coverage": "external_google_one"},
        {"name": "ultra_upsell", "label": "升级到 Google AI Ultra", "coverage": "external_google_one"},
        {"name": "notebooklm", "label": "NotebookLM", "coverage": "external_notebooklm"},
        {"name": "feedback", "label": "发送反馈", "coverage": "ui_only"},
        {"name": "help", "label": "帮助", "coverage": "ui_only"},
        {"name": "location", "label": "位置", "coverage": "ui_only"},
    ],
    "notes": [
        "Runtime model registry is still preferred when available.",
        "Drive picker, link mutation, settings mutation, and memory import mutation are not automated without a safer confirmed RPC contract.",
        "Scheduled actions support daily create and explicit delete through observed Web RPCs; edit/toggle remain disabled until stable RPC contracts are confirmed.",
        "Native Gemini Web Notebooks are covered for list, recent-chat list, and chat move operations; this is distinct from external NotebookLM.",
        "Probe tools intentionally omit raw response bodies and private account content.",
    ],
}


WEB_FEATURE_PROBES = [
    {
        "surface": "remy",
        "name": "conversation_history_recent",
        "rpcid": "MaZiqc",
        "payload": "[13,null,[false,null,true]]",
        "source_path": "/app",
        "observed": "2026-07-04 Pro UI / Conversation history recent bucket",
    },
    {
        "surface": "history",
        "name": "conversation_history_pinned",
        "rpcid": "MaZiqc",
        "payload": "[13,null,[true,null,true]]",
        "source_path": "/app",
        "observed": "2026-07-04 Pro UI / Conversation history pinned bucket",
    },
    {
        "surface": "history",
        "name": "remy_goals",
        "rpcid": "GS7W1",
        "payload": "[13]",
        "source_path": "/app",
        "observed": "2026-07-04 Pro UI / Remy goals with conversation references",
    },
    {
        "surface": "library",
        "name": "library_index",
        "rpcid": "sJBwce",
        "payload": "[[1,2]]",
        "source_path": "/app/library",
        "observed": "2026-06-18 Pro UI / Library",
    },
    {
        "surface": "library",
        "name": "library_assets",
        "rpcid": "VxUbXb",
        "payload": "[]",
        "source_path": "/app/library",
        "observed": "2026-06-18 Pro UI / Library",
    },
    {
        "surface": "library",
        "name": "library_locale_capabilities",
        "rpcid": "cYRIkd",
        "payload": '["zh-CN"]',
        "source_path": "/app/library",
        "observed": "2026-06-18 Pro UI / Library",
    },
    {
        "surface": "notebooks",
        "name": "native_notebooks_list",
        "rpcid": "CNgdBe",
        "payload": '[2,["zh-CN"],false,null,[2]]',
        "source_path": "/notebooks/view",
        "observed": "2026-07-04 Pro UI / Native Gemini Notebooks",
    },
    {
        "surface": "sharing",
        "name": "public_links_index",
        "rpcid": "K4WWud",
        "payload": '[[1],["zh-CN"]]',
        "source_path": "/app/sharing",
        "observed": "2026-06-18 Pro UI / Your public links",
    },
    {
        "surface": "sharing",
        "name": "sharing_state",
        "rpcid": "GPRiHf",
        "payload": "[]",
        "source_path": "/app/sharing",
        "observed": "2026-06-18 Pro UI / Your public links",
    },
    {
        "surface": "sharing",
        "name": "sharing_preferences",
        "rpcid": "maGuAc",
        "payload": "[1]",
        "source_path": "/app/sharing",
        "observed": "2026-06-18 Pro UI / Your public links",
    },
    {
        "surface": "usage",
        "name": "usage_quota",
        "rpcid": "qpEbW",
        "payload": "[[[1,11],[2,11],[6,11]]]",
        "source_path": "/app/usage",
        "observed": "2026-06-18 Pro UI / Usage limits",
    },
    {
        "surface": "usage",
        "name": "usage_model_state",
        "rpcid": "qpEbW",
        "payload": "[[[1,4],[6,6],[1,15]]]",
        "source_path": "/app/usage",
        "observed": "2026-06-18 Pro UI / Usage limits",
    },
    {
        "surface": "personalization",
        "name": "personalization_state",
        "rpcid": "GPRiHf",
        "payload": "[]",
        "source_path": "/app/personalization-settings",
        "observed": "2026-06-18 Pro UI / Personalization settings",
    },
    {
        "surface": "personalization",
        "name": "personalization_preferences",
        "rpcid": "maGuAc",
        "payload": "[1]",
        "source_path": "/app/personalization-settings",
        "observed": "2026-06-18 Pro UI / Personalization settings",
    },
    {
        "surface": "personalization",
        "name": "personalization_labels",
        "rpcid": "Te6DCf",
        "payload": '[["zh-CN"],[1]]',
        "source_path": "/app/personalization-settings",
        "observed": "2026-06-18 Pro UI / Personalization settings",
    },
    {
        "surface": "import",
        "name": "memory_import_state",
        "rpcid": "Te6DCf",
        "payload": '[["zh-CN"],[1]]',
        "source_path": "/app/import",
        "observed": "2026-06-18 Pro UI / Memory import",
    },
    {
        "surface": "scheduled",
        "name": "scheduled_actions_registry",
        "rpcid": "XPSWpd",
        "payload": "[]",
        "source_path": "/scheduled",
        "observed": "2026-06-19 Pro UI / Scheduled actions registry",
    },
    {
        "surface": "scheduled",
        "name": "scheduled_actions_state",
        "rpcid": "otAQ7b",
        "payload": "[]",
        "source_path": "/scheduled",
        "observed": "2026-06-18 Pro UI / Scheduled actions",
    },
    {
        "surface": "scheduled",
        "name": "scheduled_actions_active",
        "rpcid": "MaZiqc",
        "payload": "[13,null,[1,null,1]]",
        "source_path": "/scheduled",
        "observed": "2026-06-18 Pro UI / Scheduled actions",
    },
    {
        "surface": "scheduled",
        "name": "scheduled_actions_inactive",
        "rpcid": "MaZiqc",
        "payload": "[13,null,[0,null,1]]",
        "source_path": "/scheduled",
        "observed": "2026-06-18 Pro UI / Scheduled actions",
    },
    {
        "surface": "tool_modes",
        "name": "tool_mode_status",
        "rpcid": "MyzX6c",
        "payload": "[]",
        "source_path": "/app",
        "observed": "2026-06-19 Pro UI / Canvas and Guided Learning tool mode toggles",
    },
]


TOOL_MANIFEST: list[dict[str, Any]] = [
    {
        "name": "gemini_chat",
        "group": "core",
        "purpose": "One-shot Gemini Web chat with model, thinking_level, Gem, image, temporary chat, and learning_mode options.",
        "read_only": False,
        "destructive": False,
        "privacy": "sends_user_prompt_and_optional_files",
        "pagination": False,
    },
    {
        "name": "gemini_chat_stream",
        "group": "core",
        "purpose": "Streaming one-shot Gemini Web chat with the same request controls as gemini_chat.",
        "read_only": False,
        "destructive": False,
        "privacy": "sends_user_prompt_and_optional_files",
        "pagination": False,
    },
    {
        "name": "gemini_start_chat",
        "group": "core",
        "purpose": "Create a local multi-turn session backed by Gemini Web; can retain or schedule cleanup of the remote chat.",
        "read_only": False,
        "destructive": False,
        "privacy": "sends_user_prompt_when_initial_message_is_provided",
        "pagination": False,
    },
    {
        "name": "gemini_send_message",
        "group": "core",
        "purpose": "Send a message to an existing local session.",
        "read_only": False,
        "destructive": False,
        "privacy": "sends_user_prompt_and_optional_files",
        "pagination": False,
    },
    {
        "name": "gemini_send_message_stream",
        "group": "core",
        "purpose": "Stream a response from an existing local session.",
        "read_only": False,
        "destructive": False,
        "privacy": "sends_user_prompt_and_optional_files",
        "pagination": False,
    },
    {
        "name": "gemini_list_sessions",
        "group": "core",
        "purpose": "List local in-process sessions only.",
        "read_only": True,
        "destructive": False,
        "privacy": "local_session_metadata",
        "pagination": False,
    },
    {
        "name": "gemini_reset_session",
        "group": "core",
        "purpose": "Reset a local session and optionally delete its remote Gemini Web chat.",
        "read_only": False,
        "destructive": True,
        "privacy": "local_session_metadata",
        "pagination": False,
    },
    {
        "name": "gemini_generate_media",
        "group": "media",
        "purpose": "Generate image, video, or music through Gemini Web generation surfaces.",
        "read_only": False,
        "destructive": False,
        "privacy": "sends_user_prompt_and_optional_reference_files",
        "pagination": False,
    },
    {
        "name": "gemini_generate_music",
        "group": "media",
        "purpose": "Convenience music-generation wrapper using the observed Flash/Pro backend split.",
        "read_only": False,
        "destructive": False,
        "privacy": "sends_user_prompt",
        "pagination": False,
    },
    {
        "name": "gemini_upload_file",
        "group": "files",
        "purpose": "Upload and analyze a local file through Gemini Web.",
        "read_only": False,
        "destructive": False,
        "privacy": "sends_local_file_content",
        "pagination": False,
    },
    {
        "name": "gemini_analyze_url",
        "group": "files",
        "purpose": "Ask Gemini Web to analyze a URL.",
        "read_only": False,
        "destructive": False,
        "privacy": "sends_url_to_gemini",
        "pagination": False,
    },
    {
        "name": "gemini_deep_research",
        "group": "research",
        "purpose": "Run the Gemini Web Deep Research planning and report workflow.",
        "read_only": False,
        "destructive": False,
        "privacy": "sends_research_query",
        "pagination": False,
    },
    {
        "name": "gemini_list_research_report_actions",
        "group": "research",
        "purpose": "List MCP-supported create actions for a completed Gemini Web Deep Research immersive report.",
        "read_only": True,
        "destructive": False,
        "privacy": "reads_private_chat_text",
        "pagination": False,
    },
    {
        "name": "gemini_create_from_research_report",
        "group": "research",
        "purpose": "Create a local artifact matching observed Gemini Web report create-menu items: webpage, infographic, quiz, flashcards, audio overview, or custom app spec.",
        "read_only": False,
        "destructive": False,
        "privacy": "reads_private_chat_text_and_writes_local_file",
        "pagination": False,
    },
    {
        "name": "gemini_history",
        "group": "history",
        "purpose": "Read-only facade for Gemini chat history list, deep metadata scan, search, read, and export actions.",
        "read_only": True,
        "destructive": False,
        "privacy": "reads_private_chat_metadata_and_optional_turn_text",
        "pagination": True,
    },
    {
        "name": "gemini_cleanup_test_artifacts",
        "group": "history",
        "purpose": "Find and optionally delete test chats and scheduled actions whose metadata matches explicit test markers.",
        "read_only": False,
        "destructive": True,
        "privacy": "reads_private_chat_and_scheduled_metadata",
        "pagination": False,
    },
    {
        "name": "gemini_list_chats",
        "group": "history",
        "purpose": "List Gemini Web chat-history metadata.",
        "read_only": True,
        "destructive": False,
        "privacy": "reads_private_chat_metadata",
        "pagination": True,
    },
    {
        "name": "gemini_scan_chat_history_sources",
        "group": "history",
        "purpose": "Deep-scan Gemini Web chat-history metadata sources and report coverage across observed RPC filters.",
        "read_only": True,
        "destructive": False,
        "privacy": "reads_private_chat_metadata",
        "pagination": True,
    },
    {
        "name": "gemini_search_chats",
        "group": "history",
        "purpose": "Search chat titles/IDs by default; scan turn text only when scan_turns=true.",
        "read_only": True,
        "destructive": False,
        "privacy": "reads_private_chat_metadata_and_optional_turn_text",
        "pagination": True,
    },
    {
        "name": "gemini_read_chat",
        "group": "history",
        "purpose": "Read turns from a selected Gemini Web chat.",
        "read_only": True,
        "destructive": False,
        "privacy": "reads_private_chat_text",
        "pagination": True,
    },
    {
        "name": "gemini_export_chat",
        "group": "history",
        "purpose": "Export one selected Gemini Web chat as Markdown or JSON.",
        "read_only": True,
        "destructive": False,
        "privacy": "reads_private_chat_text",
        "pagination": True,
    },
    {
        "name": "gemini_delete_chat",
        "group": "history",
        "purpose": "Delete a selected remote Gemini Web chat.",
        "read_only": False,
        "destructive": True,
        "privacy": "uses_private_chat_id",
        "pagination": False,
    },
    {
        "name": "gemini_inspect_account",
        "group": "account",
        "purpose": "Inspect account feature/RPC status without raw RPC previews.",
        "read_only": True,
        "destructive": False,
        "privacy": "reads_sanitized_account_status",
        "pagination": False,
    },
    {
        "name": "gemini_get_web_capabilities",
        "group": "account",
        "purpose": "Return the observed Gemini Web Pro capability map and MCP coverage.",
        "read_only": True,
        "destructive": False,
        "privacy": "static_no_account_content",
        "pagination": False,
    },
    {
        "name": "gemini_get_tool_manifest",
        "group": "account",
        "purpose": "Return this agent-facing tool manifest with safety, privacy, and workflow metadata.",
        "read_only": True,
        "destructive": False,
        "privacy": "static_no_account_content",
        "pagination": False,
    },
    {
        "name": "gemini_probe_web_features",
        "group": "account",
        "purpose": "Probe observed read-only Gemini Web RPC reachability without returning raw bodies.",
        "read_only": True,
        "destructive": False,
        "privacy": "reads_rpc_status_only",
        "pagination": False,
    },
    {
        "name": "gemini_account_inventory",
        "group": "account",
        "purpose": "Read-only facade for account inventory surfaces such as capabilities, links, usage, library, notebooks, scheduled entries, modes, and models.",
        "read_only": True,
        "destructive": False,
        "privacy": "reads_private_account_inventory",
        "pagination": True,
    },
    {
        "name": "gemini_list_public_links",
        "group": "account",
        "purpose": "List Gemini Web public-link entries.",
        "read_only": True,
        "destructive": False,
        "privacy": "reads_private_public_link_index",
        "pagination": True,
    },
    {
        "name": "gemini_get_usage_limits",
        "group": "account",
        "purpose": "Read Gemini Web usage/quota structures.",
        "read_only": True,
        "destructive": False,
        "privacy": "reads_private_usage_state",
        "pagination": False,
    },
    {
        "name": "gemini_list_library_capabilities",
        "group": "account",
        "purpose": "List localized Library capability/template entries, not private Library assets.",
        "read_only": True,
        "destructive": False,
        "privacy": "reads_template_capabilities",
        "pagination": True,
    },
    {
        "name": "gemini_notebooks",
        "group": "account",
        "purpose": "Read-only facade for native Gemini Web Notebook list and notebook-chat metadata.",
        "read_only": True,
        "destructive": False,
        "privacy": "reads_private_notebook_metadata",
        "pagination": True,
    },
    {
        "name": "gemini_list_notebooks",
        "group": "account",
        "purpose": "List native Gemini Web Notebooks with ids, titles, emoji, source counts, and subtype metadata.",
        "read_only": True,
        "destructive": False,
        "privacy": "reads_private_notebook_metadata",
        "pagination": True,
    },
    {
        "name": "gemini_list_notebook_chats",
        "group": "account",
        "purpose": "List recent Gemini Web chats already assigned to a native notebook.",
        "read_only": True,
        "destructive": False,
        "privacy": "reads_private_notebook_chat_metadata",
        "pagination": True,
    },
    {
        "name": "gemini_move_chat_to_notebook",
        "group": "account",
        "purpose": "Move an existing Gemini Web chat into a native Gemini Web Notebook using the observed UpdateConversation RPC.",
        "read_only": False,
        "destructive": False,
        "privacy": "moves_private_chat_metadata",
        "pagination": False,
    },
    {
        "name": "gemini_list_scheduled_actions",
        "group": "account",
        "purpose": "Read active/inactive scheduled-action entries.",
        "read_only": True,
        "destructive": False,
        "privacy": "reads_private_scheduled_action_titles",
        "pagination": True,
    },
    {
        "name": "gemini_get_scheduled_action",
        "group": "account",
        "purpose": "Read one scheduled action by id using the observed Web GetTask RPC.",
        "read_only": True,
        "destructive": False,
        "privacy": "reads_private_scheduled_action_details",
        "pagination": False,
    },
    {
        "name": "gemini_create_scheduled_action",
        "group": "account",
        "purpose": "Create a daily Gemini Web scheduled action through the observed scheduled-actions RPC.",
        "read_only": False,
        "destructive": False,
        "privacy": "creates_private_scheduled_action",
        "pagination": False,
    },
    {
        "name": "gemini_delete_scheduled_action",
        "group": "account",
        "purpose": "Delete a Gemini Web scheduled action by id through the observed scheduled-actions RPC.",
        "read_only": False,
        "destructive": True,
        "privacy": "deletes_private_scheduled_action",
        "pagination": False,
    },
    {
        "name": "gemini_get_tool_mode_status",
        "group": "account",
        "purpose": "Read Web-internal Canvas/Guided Learning mode status rows.",
        "read_only": True,
        "destructive": False,
        "privacy": "reads_mode_status_only",
        "pagination": True,
    },
    {
        "name": "gemini_list_models",
        "group": "account",
        "purpose": "List MCP model aliases and runtime model registry.",
        "read_only": True,
        "destructive": False,
        "privacy": "reads_account_model_registry",
        "pagination": False,
    },
    {
        "name": "gemini_manage_gems",
        "group": "gems",
        "purpose": "List, create, update, or delete Gems depending on action.",
        "read_only": False,
        "destructive": True,
        "privacy": "reads_or_modifies_private_gems",
        "pagination": False,
    },
    {
        "name": "gemini_doctor",
        "group": "cookie",
        "purpose": "Run a safe local preflight over tool groups, cookie status, browser profile alignment, and media verification dependencies.",
        "read_only": True,
        "destructive": False,
        "privacy": "local_runtime_and_browser_profile_diagnostics",
        "pagination": False,
    },
    {
        "name": "gemini_get_cookie_status",
        "group": "cookie",
        "purpose": "Report local cookie availability without printing cookie values.",
        "read_only": True,
        "destructive": False,
        "privacy": "local_auth_status_only",
        "pagination": False,
    },
    {
        "name": "gemini_list_browser_cookie_profiles",
        "group": "cookie",
        "purpose": "List local browser cookie profiles and validation diagnostics without printing cookie values.",
        "read_only": True,
        "destructive": False,
        "privacy": "local_browser_profile_auth_diagnostics",
        "pagination": False,
    },
    {
        "name": "gemini_get_cookie_from_browser",
        "group": "cookie",
        "purpose": "Load Gemini cookies from a local browser/profile into the server runtime.",
        "read_only": False,
        "destructive": False,
        "privacy": "reads_local_browser_auth_secret",
        "pagination": False,
    },
    {
        "name": "gemini_reset",
        "group": "cookie",
        "purpose": "Reset the local Gemini client instance.",
        "read_only": False,
        "destructive": False,
        "privacy": "local_runtime_state",
        "pagination": False,
    },
    {
        "name": "gemini_manage_prompts",
        "group": "prompts",
        "purpose": "Manage local prompt snippets when GEMINI_TOOLS=prompts is enabled.",
        "read_only": False,
        "destructive": True,
        "privacy": "local_prompt_library",
        "pagination": False,
    },
]
